name: expertaid_lms_driver
description: ExpertaidLMS Driver Mobile Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences: ^2.3.3
  flutter_secure_storage: ^9.2.2
  provider: ^6.1.2
  intl: ^0.19.0
  fl_chart: ^0.69.2
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  flutter_slidable: ^3.1.1
  badges: ^3.1.2
  animations: ^2.0.11
  table_calendar: ^3.1.2
  geolocator: ^13.0.2
  google_maps_flutter: ^2.10.0
  location: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
